import Link from "next/link";
import directus from '../lib/directus';
import { readItems, readMe } from '@directus/sdk/rest';
import { authentication } from '@directus/sdk';
import Cookies from 'js-cookie';
import Auth from './auth/Auth'
import { cookies } from 'next/headers'

export const fetchCache = "force-no-store";

export const metadata = {
  title: 'Strona glowna',
  description: 'Generated by Next.js',
}

export default async function RootLayout({children}) {
  const cookiesList = cookies();
  let token = null;
  let user = null;
  const hasToken = cookiesList.has('token');
  if (hasToken) {
    token = cookiesList.get('token').value;
    let directusAuth = directus.with(authentication('json'));

    await directusAuth.setToken(token);    
    user = await directusAuth.request(
      readMe({
        fields: ['*'],
      })
    );
    console.log(children);
  }

  // const user = await getAuth();
  return (
		<html lang="pl">
			<body>
        <Auth token={token} user={user} />
				<nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/contact">Contact</Link></li>
            <li><Link href="/blog">Blog</Link></li>
          </ul>
				</nav>
				<main>{children}</main>
			</body>
		</html>
  )
}
